num1 = int(input())
num2 = int(input())
num3 = int(input())
num4 = int(input())
num5 = int(input())
num6 = int(input())
num7 = int(input())

print(num1)
print(num2)
print(num3)
print(num4)
print(num5)
print(num6)
print(num7)
